#pragma once

#include <bsplines/BSpline.hpp>

#include <ceres/jet.h>

#include <Eigen/Core>

#include <algorithm>
#include <cmath>
#include <stdexcept>
#include <utility>
#include <vector>

namespace kalibr::ceres_optimizer {

// Read-only copy of the exact basis matrices generated by Kalibr's BSpline.
// Unlike BSpline::evalD(), evaluateParameters() accepts a Ceres Jet timestamp,
// which is required to differentiate camera-to-IMU time offset.
class DynamicSpline {
 public:
  explicit DynamicSpline(const bsplines::BSpline& spline);

  int order() const { return order_; }
  int controlCount() const {
    return static_cast<int>(knots_.size()) - order_;
  }
  double minimumTime() const { return knots_.at(order_ - 1); }
  double maximumTime() const { return knots_.at(knots_.size() - order_); }
  int segmentForTime(double timestamp) const;
  std::pair<int, int> candidateControls(double minimum_time,
                                        double maximum_time) const;

  template <typename T>
  Eigen::Matrix<T, Eigen::Dynamic, 1> evaluateParameters(
      const T& timestamp, int derivative_order, T const* const* parameters,
      int first_parameter_control, int dimension) const {
    if (derivative_order < 0 || derivative_order >= order_)
      throw std::invalid_argument("Invalid B-spline derivative order");
    const int segment = segmentForTime(scalarPart(timestamp));
    const int first_control = segment - order_ + 1;
    const int parameter_offset = first_control - first_parameter_control;
    if (parameter_offset < 0 ||
        parameter_offset + order_ >
            controlCount() - first_parameter_control) {
      throw std::out_of_range(
          "Ceres residual does not contain the active spline controls");
    }
    const double width = knots_[segment + 1] - knots_[segment];
    if (width <= 0.0)
      throw std::runtime_error("Kalibr spline contains an empty segment");
    const T normalized_time =
        (timestamp - T(knots_[segment])) / T(width);
    Eigen::Matrix<T, Eigen::Dynamic, 1> powers(order_);
    powers.setZero();
    T power = T(1);
    for (int index = derivative_order; index < order_; ++index) {
      powers[index] = power * T(derivativeMultiplier(
                                     index, derivative_order)) /
          T(std::pow(width, derivative_order));
      power *= normalized_time;
    }
    const Eigen::Matrix<T, Eigen::Dynamic, 1> weights =
        basis_matrices_[first_control].template cast<T>().transpose() * powers;
    Eigen::Matrix<T, Eigen::Dynamic, 1> result(dimension);
    result.setZero();
    for (int control = 0; control < order_; ++control) {
      const T* values = parameters[parameter_offset + control];
      for (int row = 0; row < dimension; ++row)
        result[row] += weights[control] * values[row];
    }
    return result;
  }

 private:
  static double scalarPart(double value) { return value; }
  template <typename T, int Dimension>
  static double scalarPart(const ceres::Jet<T, Dimension>& value) {
    return value.a;
  }
  static int derivativeMultiplier(int power, int derivative_order);

  int order_;
  std::vector<double> knots_;
  std::vector<Eigen::MatrixXd> basis_matrices_;
};

}  // namespace kalibr::ceres_optimizer
