schema_version: 1
job: camera_calibration

dataset:
  type: bag
  path: data/camera.bag

target:
  path: config/aprilgrid.yaml

cameras:
  - {topic: /cam0/image_raw, model: pinhole-radtan5}
  - {topic: /cam1/image_raw, model: pinhole-radtan5}

calibration:
  shuffle: false
